import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";
import routerConfig from "@/components/routerConfig";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}

const navLinks = [
  routerConfig.contact,
  routerConfig.services,
  routerConfig.solutions,
  routerConfig.projects,
  routerConfig.news,
  routerConfig.esg,
  routerConfig.careers,
]

function Footer() {
  return (
    <footer className="bg-[#0A85D1] text-white py-4">
      <div className="container mx-auto px-4">
        <div className="flex flex-wrap justify-between items-center">
          <div className="flex items-center space-x-8">
            {navLinks.map((link) => (
              <a href={link.href} className="text-sm hover:underline" key={link.href}>{link.label}</a>
            ))}
          </div>

          <div className="flex items-center space-x-2">
            <a href="#" aria-label="Facebook" className="w-6 h-6 flex items-center justify-center bg-gray-500 rounded-full">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fillRule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clipRule="evenodd" />
              </svg>
            </a>
            <a href="#" aria-label="YouTube" className="w-6 h-6 flex items-center justify-center bg-gray-500 rounded-full">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fillRule="evenodd" d="M19.812 5.418c.861.23 1.538.907 1.768 1.768C21.998 8.746 22 12 22 12s0 3.255-.418 4.814a2.504 2.504 0 0 1-1.768 1.768c-1.56.419-7.814.419-7.814.419s-6.255 0-7.814-.419a2.505 2.505 0 0 1-1.768-1.768C2 15.255 2 12 2 12s0-3.255.417-4.814a2.507 2.507 0 0 1 1.768-1.768C5.744 5 11.998 5 11.998 5s6.255 0 7.814.418z" clipRule="evenodd" />
                <path d="M15.194 12 10 15V9l5.194 3z" />
              </svg>
            </a>
          </div>
        </div>

        <div className="flex items-center mt-4">
          <div className="flex items-center">
            <div className="mr-2">
              <p className="text-sm">© 2024 智兆科技股份有限公司</p>
            </div>
            <div>
              <p className="text-sm">
                地址：台北市中山區中山北路一段123號
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
